import { DUMMY_ROAST } from './_data/dummy';
import { RoastHeader } from './_components/RoastHeader';
import { ScoreRing } from './_components/ScoreRing';
import { SummaryCard } from './_components/SummaryCard';
import { Observations } from './_components/Observations';
import { SecurityFindings } from './_components/SecurityFindings';
import { DevProfileCard } from './_components/DevProfile';
import { TableOfContents } from './_components/TableOfContents';

export default function RoastPage() {
  const roast = DUMMY_ROAST;

  return (
    <div className="min-h-screen bg-[#0F0F0F] py-12 px-6">
      <div className="max-w-2xl mx-auto">

        <div className="mb-8">
          <RoastHeader repo={roast.repo} />
        </div>

        <div className="space-y-6">
            <div id="scores" className="rounded-xl border border-[#2A2A2A] bg-[#141414] p-6 scroll-mt-8">
              <div className="flex justify-around">
                <ScoreRing score={roast.overallScore} label="Overall" />
                <ScoreRing score={roast.codeQualityScore} label="Code Quality" />
                <ScoreRing score={roast.securityScore} label="Security" />
              </div>
            </div>

            <div id="summary"><SummaryCard summary={roast.roastSummary} /></div>
            <div id="developer"><DevProfileCard profile={roast.devProfile} /></div>
            <div id="observations"><Observations observations={roast.funnyObservations} /></div>
            <div id="security"><SecurityFindings findings={roast.securityFindings} /></div>

            <p className="text-center text-xs text-[#2A2A2A] pb-4">
              Generated by Singe &mdash; powered by Claude AI
            </p>
        </div>

        <TableOfContents />

      </div>
    </div>
  );
}
